// <auto-generated />
using System;
using GlucoCare.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GlucoCare.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GlucoCare.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal>("InsulinSensibility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucose", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BloodGlocoseStatus")
                        .HasColumnType("int");

                    b.Property<int>("BloodGlucosesRecodId")
                        .HasColumnType("int");

                    b.Property<int?>("BloodGlucosesRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentGlucoseLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InjectedInsulinId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodGlucosesRecordId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("BloodGlucoses");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucosesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("BloodGlucosesRecords");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CarbohydrateIntakesRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarbohydrateIntakesRecordId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("CarbohidrateIntakes");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntakeInjectedInsulin", b =>
                {
                    b.Property<int>("CarbohidrateIntakeId")
                        .HasColumnType("int");

                    b.Property<int>("InjectedInsulinId")
                        .HasColumnType("int");

                    b.HasKey("CarbohidrateIntakeId", "InjectedInsulinId");

                    b.HasIndex("InjectedInsulinId");

                    b.ToTable("CarbohydrateIntakeInjectedInsulin");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntakesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiabeticId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiabeticId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("CarbohydrateIntakesRecords");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("CaloriesPer100Grams")
                        .HasColumnType("float");

                    b.Property<int>("CarbohidrateIntakeId")
                        .HasColumnType("int");

                    b.Property<double>("CarbohydratePer100Grams")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("FatPer100Grams")
                        .HasColumnType("float");

                    b.Property<string>("FoodImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodPlanId")
                        .HasColumnType("int");

                    b.Property<int>("FoodType")
                        .HasColumnType("int");

                    b.Property<int>("GlycemicIndex")
                        .HasColumnType("int");

                    b.Property<int>("Grams")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("ProteinPer100Grams")
                        .HasColumnType("float");

                    b.Property<double>("WaterPer100Grams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CarbohidrateIntakeId");

                    b.HasIndex("FoodPlanId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.FoodPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("FoodPlans");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BloodGlucoseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hour")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InjectedInsulinsRecordId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("InjectionTimeBeforeEating")
                        .HasColumnType("time");

                    b.Property<int>("InsulinDose")
                        .HasColumnType("int");

                    b.Property<int>("InsulinId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsulinRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BloodGlucoseId")
                        .IsUnique();

                    b.HasIndex("InjectedInsulinsRecordId");

                    b.HasIndex("InsulinId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SportActivityId");

                    b.ToTable("InjectedInsulins");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulinsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("InjectedInsulinsRecords");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.Insulin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsulinActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsulinType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Insulins");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.SportActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ActivityLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsulinNeedId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InsulinNeedId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("SportActivities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucose", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.BloodGlucosesRecord", "BloodGlucosesRecord")
                        .WithMany("BloodGlucoses")
                        .HasForeignKey("BloodGlucosesRecordId");

                    b.Navigation("BloodGlucosesRecord");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucosesRecord", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", "User")
                        .WithMany("BloodGlucosesRecords")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntake", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.CarbohydrateIntakesRecord", "CarbohydrateIntakesRecord")
                        .WithMany("CarbohydrateIntakes")
                        .HasForeignKey("CarbohydrateIntakesRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarbohydrateIntakesRecord");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntakeInjectedInsulin", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.CarbohydrateIntake", "CarbohidrateIntake")
                        .WithMany("Insulins")
                        .HasForeignKey("CarbohidrateIntakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoCare.Data.Models.InjectedInsulin", "InjectedInsulin")
                        .WithMany("CarbohydrateIntakes")
                        .HasForeignKey("InjectedInsulinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarbohidrateIntake");

                    b.Navigation("InjectedInsulin");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntakesRecord", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", "Diabetic")
                        .WithMany("CarbohydrateIntakesRecords")
                        .HasForeignKey("DiabeticId");

                    b.Navigation("Diabetic");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.Food", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.CarbohydrateIntake", "CarbohidrateIntake")
                        .WithMany("Foods")
                        .HasForeignKey("CarbohidrateIntakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoCare.Data.Models.FoodPlan", "FoodPlan")
                        .WithMany("Foods")
                        .HasForeignKey("FoodPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CarbohidrateIntake");

                    b.Navigation("FoodPlan");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.FoodPlan", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulin", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.BloodGlucose", "BloodGlucose")
                        .WithOne("InjectedInsulin")
                        .HasForeignKey("GlucoCare.Data.Models.InjectedInsulin", "BloodGlucoseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoCare.Data.Models.InjectedInsulinsRecord", null)
                        .WithMany("InjectedInsulins")
                        .HasForeignKey("InjectedInsulinsRecordId");

                    b.HasOne("GlucoCare.Data.Models.Insulin", "Insulin")
                        .WithMany()
                        .HasForeignKey("InsulinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoCare.Data.Models.SportActivity", "SportActivity")
                        .WithMany()
                        .HasForeignKey("SportActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BloodGlucose");

                    b.Navigation("Insulin");

                    b.Navigation("SportActivity");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulinsRecord", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", "User")
                        .WithMany("InjectedInsulinRecords")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.SportActivity", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.InjectedInsulin", "InsulinNeed")
                        .WithMany()
                        .HasForeignKey("InsulinNeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InsulinNeed");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GlucoCare.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GlucoCare.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("BloodGlucosesRecords");

                    b.Navigation("CarbohydrateIntakesRecords");

                    b.Navigation("Claims");

                    b.Navigation("InjectedInsulinRecords");

                    b.Navigation("Logins");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucose", b =>
                {
                    b.Navigation("InjectedInsulin");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.BloodGlucosesRecord", b =>
                {
                    b.Navigation("BloodGlucoses");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntake", b =>
                {
                    b.Navigation("Foods");

                    b.Navigation("Insulins");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.CarbohydrateIntakesRecord", b =>
                {
                    b.Navigation("CarbohydrateIntakes");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.FoodPlan", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulin", b =>
                {
                    b.Navigation("CarbohydrateIntakes");
                });

            modelBuilder.Entity("GlucoCare.Data.Models.InjectedInsulinsRecord", b =>
                {
                    b.Navigation("InjectedInsulins");
                });
#pragma warning restore 612, 618
        }
    }
}
